changelog:
  categories:
    - title: Frontend
      labels:
        - ui
        - frontend
    - title: Protocol Docs
      labels:
        - documentation
        - docs
    - title: Automation
      labels:
        - ci
        - infra
        - release
    - title: Other
      labels:
        - "*"
